version = 0.1
[default.deploy.parameters]
stack_name = "dev-sale-server"
s3_prefix = "sale-server"
resolve_s3 = true
region = "ap-northeast-1"
confirm_changeset = true
no_fail_on_empty_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = """
EnvName=dev \
ApiDomainName=dev-sale-api.akiho.app \
HostedZoneName=akiho.app. \
CertificateArn=arn:aws:acm:ap-northeast-1:326914400610:certificate/cc857fc9-2676-4fdd-90fc-8e989b5e2506 \
"""