[package]
name = "crawler-rakuten"
version = "0.1.0"
edition = "2021"

[dependencies]
sale = { path = "../sale" }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.8", features = ["blocking", "rustls-tls", "json"] }
scraper = "0.20.0"